--**
--CreateTablesLivretVCIM_SQL.sql
--JFO 26/06/2006 : traitement post-SQL pr‚-ORACLE sur BARBARA
/* Microsoft SQL Server - Scripting			*/
/* Server: NEWTON					*/
/* Database: Prod_RubisInfocentreProduit					*/
/* Creation Date 25/03/2004 17:18:22 			*/
use RubisInfoCentreProduit

ALTER TABLE [dbo].[COMPOHOP] DROP CONSTRAINT FK_COMPOHOP_LIEN_13_SPEPRESE
GO

ALTER TABLE [dbo].[COMPOVIDAL] DROP CONSTRAINT FK_COMPOVID_LIEN_116_SPEPRESE
GO

ALTER TABLE [dbo].[LIVRETHOP] DROP CONSTRAINT FK_LIVRETHO_ASSOC_122_SPEPRESE
GO

ALTER TABLE [dbo].[COMPOHOP] DROP CONSTRAINT FK_COMPOHOP_LIEN_14_T_SUBHOP
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[LIVRETHOP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LIVRETHOP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[LIVRETHOPTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LIVRETHOPTEMP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[LivretLog]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LivretLog]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[LIVRETVIDAL]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LIVRETVIDAL]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[LIVRETVIDALTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[LIVRETVIDALTEMP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[SPEPRESENTATIONHOP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[SPEPRESENTATIONHOP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[SPEPRESENTATIONHOPTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[SPEPRESENTATIONHOPTEMP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[T_SUBHOP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[T_SUBHOP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[T_SUBHOPTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[T_SUBHOPTEMP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[tampon]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tampon]
GO


if exists (select * from sysobjects where id = object_id(N'[dbo].[COMPOHOP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMPOHOP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[COMPOHOPTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMPOHOPTEMP]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[COMPOVIDAL]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMPOVIDAL]
GO

if exists (select * from sysobjects where id = object_id(N'[dbo].[COMPOVIDALTEMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[COMPOVIDALTEMP]
GO

CREATE TABLE [dbo].[LIVRETHOP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[PRIX_TTC_F] [T_OVP_FLOAT] NULL ,
	[PRIX_TTC_E] [T_OVP_FLOAT] NULL ,
	[DISPO] [T_libelle60] NULL ,
	[COMMENTAIRE] [T_TEXTE_LONG] NULL ,
	[CODHOPITAL] [T_libelle30] NULL 
)
GO

CREATE TABLE [dbo].[LIVRETHOPTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[PRIX_TTC_F] [T_OVP_FLOAT] NULL ,
	[PRIX_TTC_E] [T_OVP_FLOAT] NULL ,
	[DISPO] [T_libelle60] NULL ,
	[COMMENTAIRE] [T_MEMO] NULL ,
	[CODHOPITAL] [T_libelle30] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[LivretLog] (
	[CIP] [varchar] (10) NULL ,
	[Nom] [varchar] (255) NULL ,
	[CodeErreur] [varchar] (10) NULL ,
	[TexteErreur] [varchar] (2000) NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LIVRETVIDAL] (
	[ID_SPEPRESENTATION] [T_OVP_ENTIERS] NOT NULL ,
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[PRIX_TTC_F] [T_OVP_FLOAT] NULL ,
	[PRIX_TTC_E] [T_OVP_FLOAT] NULL ,
	[DISPO] [T_libelle60] NULL ,
	[COMMENTAIRE] [T_TEXTE_LONG] NULL ,
	[DENOM_HOP] [T_libelle200] NULL ,
	[UCD_HOP] [T_libelle7] NULL ,
	[CODHOPITAL] [T_libelle30] NULL 
)
GO

CREATE TABLE [dbo].[LIVRETVIDALTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[CIP] [T_libelle7] NOT NULL ,
	[PRIX_TTC_F] [T_OVP_FLOAT] NULL ,
	[PRIX_TTC_E] [T_OVP_FLOAT] NULL ,
	[DISPO] [T_libelle60] NULL ,
	[COMMENTAIRE] [T_MEMO] NULL ,
	[DENOM_HOP] [T_libelle50] NULL ,
	[UCD_HOP] [T_libelle7] NULL ,
	[CODHOPITAL] [T_libelle30] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPEPRESENTATIONHOP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_COMPTEUR] IDENTITY (1, 1) NOT NULL ,
	[NOM] [T_libelle200] NULL ,
	[PRESENTATION] [T_libelle50] NULL ,
	[FORME] [T_libelle50] NULL ,
	[DOSAGE] [T_libelle50] NULL ,
	[CIP] [T_libelle7] NULL ,
	[UCD] [T_libelle7] NULL ,
	[LABO] [T_libelle60] NULL 
)
GO

CREATE TABLE [dbo].[SPEPRESENTATIONHOPTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_COMPTEUR] NOT NULL ,
	[NOM] [T_libelle50] NULL ,
	[PRESENTATION] [T_libelle50] NULL ,
	[FORME] [T_libelle50] NULL ,
	[DOSAGE] [T_libelle50] NULL ,
	[CIP] [T_libelle7] NULL ,
	[UCD] [T_libelle7] NULL ,
	[LABO] [T_libelle60] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_SUBHOP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_T_SUBHOP] [T_COMPTEUR] IDENTITY (1, 1) NOT NULL ,
	[LIBELLE] [T_libelle50] NULL 
)
GO

CREATE TABLE [dbo].[T_SUBHOPTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_T_SUBHOP] [T_COMPTEUR] NOT NULL ,
	[LIBELLE] [T_libelle50] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[tampon] (
	[IDORGANISME] [T_OVP_ENTIERS] NULL ,
	[NOM] [T_libelle200] NULL ,
	[PRESENTATION] [T_libelle50] NULL ,
	[FORME] [T_libelle50] NULL ,
	[DOSAGE] [T_libelle50] NULL ,
	[CIP] [T_libelle7] NULL ,
	[UCD] [T_libelle7] NULL ,
	[LABO] [T_libelle60] NULL ,
	[CODHOPITAL] [T_libelle30] NULL ,
	[PRIX_TTC_F] [T_OVP_FLOAT] NULL ,
	[PRIX_TTC_E] [T_OVP_FLOAT] NULL ,
	[DISPO] [T_libelle60] NULL ,
	[COMMENTAIRE] [T_TEXTE_LONG] NULL ,
	[DENOM_HOP] [T_libelle200] NULL ,
	[UCD_HOP] [T_libelle7] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[COMPOHOP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[ID_T_SUBHOP] [T_OVP_ENTIERS] NOT NULL 
)
GO

CREATE TABLE [dbo].[COMPOHOPTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[ID_T_SUBHOP] [T_OVP_ENTIERS] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[COMPOVIDAL] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[ID_T_SUB] [T_OVP_ENTIERS] NOT NULL 
)
GO

CREATE TABLE [dbo].[COMPOVIDALTEMP] (
	[IDORGANISME] [T_OVP_ENTIERS] NOT NULL ,
	[ID_SPEPRESENTATIONHOP] [T_OVP_ENTIERS] NOT NULL ,
	[LIBELLE] [T_LIBELLE_100] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LIVRETHOP] WITH NOCHECK ADD 
	 PRIMARY KEY  CLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LIVRETVIDAL] WITH NOCHECK ADD 
	 PRIMARY KEY  CLUSTERED 
	(
		[ID_SPEPRESENTATION],
		[IDORGANISME]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPEPRESENTATIONHOP] WITH NOCHECK ADD 
	 PRIMARY KEY  CLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[T_SUBHOP] WITH NOCHECK ADD 
	 PRIMARY KEY  CLUSTERED 
	(
		[IDORGANISME],
		[ID_T_SUBHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COMPOHOP] WITH NOCHECK ADD 
	 PRIMARY KEY  CLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP],
		[ID_T_SUBHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[COMPOVIDAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_COMPOVIDAL] PRIMARY KEY  CLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP],
		[ID_T_SUB]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LIVRETHOPTEMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_LIVRETHOPTEMP] PRIMARY KEY  NONCLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LIVRETVIDALTEMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_LIVRETVIDALTEMP] PRIMARY KEY  NONCLUSTERED 
	(
		[IDORGANISME]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SPEPRESENTATIONHOPTEMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_SPEPRESENTATIONHOPTEMP] PRIMARY KEY  NONCLUSTERED 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[T_SUBHOPTEMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_T_SUBHOPTEMP] PRIMARY KEY  NONCLUSTERED 
	(
		[IDORGANISME],
		[ID_T_SUBHOP]
	)  ON [PRIMARY] 
GO


 CREATE  INDEX [ASSOC_244_FK] ON [dbo].[LIVRETVIDAL]([ID_SPEPRESENTATION]) ON [PRIMARY]
GO

 CREATE  INDEX [ASSOC_247_FK] ON [dbo].[LIVRETVIDAL]([IDORGANISME]) ON [PRIMARY]
GO

 CREATE  INDEX [ASSOC_131_FK] ON [dbo].[SPEPRESENTATIONHOP]([IDORGANISME]) ON [PRIMARY]
GO

 CREATE  INDEX [ASSOC_48_FK] ON [dbo].[T_SUBHOP]([IDORGANISME]) ON [PRIMARY]
GO


 CREATE  INDEX [LIEN_13_FK] ON [dbo].[COMPOHOP]([IDORGANISME], [ID_SPEPRESENTATIONHOP]) ON [PRIMARY]
GO

 CREATE  INDEX [LIEN_14_FK] ON [dbo].[COMPOHOP]([ID_T_SUBHOP]) ON [PRIMARY]
GO

 CREATE  INDEX [LIEN_116_FK] ON [dbo].[COMPOVIDAL]([IDORGANISME], [ID_SPEPRESENTATIONHOP]) ON [PRIMARY]
GO

 CREATE  INDEX [LIEN_117_FK] ON [dbo].[COMPOVIDAL]([ID_T_SUB]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LIVRETHOP] ADD 
	CONSTRAINT [FK_LIVRETHO_ASSOC_122_SPEPRESE] FOREIGN KEY 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	) REFERENCES [dbo].[SPEPRESENTATIONHOP] (
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	)
GO

ALTER TABLE [dbo].[LIVRETVIDAL] ADD 
	CONSTRAINT [FK_LIVRETVI_ASSOC_244_SPEPRESE] FOREIGN KEY 
	(
		[ID_SPEPRESENTATION]
	) REFERENCES [dbo].[SpePresentation] (
		[id_SpePresentation]
	)
GO

ALTER TABLE [dbo].[COMPOHOP] ADD 
	CONSTRAINT [FK_COMPOHOP_LIEN_13_SPEPRESE] FOREIGN KEY 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	) REFERENCES [dbo].[SPEPRESENTATIONHOP] (
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	),
	CONSTRAINT [FK_COMPOHOP_LIEN_14_T_SUBHOP] FOREIGN KEY 
	(
		[IDORGANISME],
		[ID_T_SUBHOP]
	) REFERENCES [dbo].[T_SUBHOP] (
		[IDORGANISME],
		[ID_T_SUBHOP]
	)
GO

ALTER TABLE [dbo].[COMPOVIDAL] ADD 
	CONSTRAINT [FK_COMPOVID_LIEN_116_SPEPRESE] FOREIGN KEY 
	(
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	) REFERENCES [dbo].[SPEPRESENTATIONHOP] (
		[IDORGANISME],
		[ID_SPEPRESENTATIONHOP]
	),
	CONSTRAINT [FK_COMPOVID_LIEN_117_T_SUB] FOREIGN KEY 
	(
		[ID_T_SUB]
	) REFERENCES [dbo].[T_Sub] (
		[id_T_Sub]
	)
GO
print 'LIVRETHOP'
select count(*) from LIVRETHOP
print 'LIVRETHOP'
select count(*) from LIVRETVIDAL
print 'LIVRETVIDAL'
select count(*) from COMPOHOP
print 'COMPOHOP'
select count(*) from COMPOVIDAL
print 'COMPOVIDAL'
select count(*) from COMPOVIDALTEMP
print 'COMPOVIDALTEMP'
select count(*) from COMPOHOPTEMP 
print 'COMPOHOPTEMP'
select count(*) from tampon
print 'tampon'
select count(*) from T_SUBHOPTEMP
print 'T_SUBHOPTEMP'
select count(*) from T_SUBHOP
print 'T_SUBHOP'
select count(*) from T_SUBHOPTEMP
print 'T_SUBHOPTEMP'
select count(*) from SPEPRESENTATIONHOPTEMP
print 'SPEPRESENTATIONHOPTEMP'
select count(*) from SPEPRESENTATIONHOP
print 'SPEPRESENTATIONHOP'
select count(*) from LIVRETVIDALTEMP
print 'LIVRETVIDALTEMP'
select count(*) from LivretLog
print 'LivretLog'
select count(*) from LIVRETHOPTEMP
print 'LIVRETHOPTEMP'